=== open-medication/open-medication-catalog/adapters/ch/swissmedic/xsd/OGD-Stoff-Synonyme.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema targetNamespace="http://ccsap.bit.admin.ch/SWISSMEDIC/LIMS_HMIT_KHZ" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://ccsap.bit.admin.ch/SWISSMEDIC/LIMS_HMIT_KHZ" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3.org/2001/XMLSchema http://www.w3.org/2001/XMLSchema.xsd">
	<xsd:element name="SMC_Synonyme" type="OGD_Synonyme"/>
	<xsd:complexType name="OGD_Synonyme">
		<xsd:sequence>
			<xsd:element name="SYNONYME" minOccurs="0" maxOccurs="unbounded" type="SYNONYME"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="SYNONYME">
		<xsd:sequence>
			<xsd:element name="STOFF_ID" type="xsd:string">
				<xsd:annotation>
					<xsd:documentation xml:lang="de">Stoff Guid</xsd:documentation>
					<xsd:documentation xml:lang="fr">Identifiant global unique de la substance</xsd:documentation>
					<xsd:documentation xml:lang="it">GUID sostanza</xsd:documentation>
					<xsd:documentation xml:lang="en">Substance GUID</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="SYNONYM_CODE" type="xsd:string">
				<xsd:annotation>
					<xsd:documentation xml:lang="de">Synonym Typ</xsd:documentation>
					<xsd:documentation xml:lang="fr">Type de synonyme</xsd:documentation>
					<xsd:documentation xml:lang="it">Tipo di sinonimo</xsd:documentation>
					<xsd:documentation xml:lang="en">Synonym type only “LN”</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="LAUFENDE_NR" type="xsd:Integer">
				<xsd:annotation>
					<xsd:documentation xml:lang="de">Synonym Nummer</xsd:documentation>
					<xsd:documentation xml:lang="fr">Numéro de synonyme</xsd:documentation>
					<xsd:documentation xml:lang="it">Numero sinonimo</xsd:documentation>
					<xsd:documentation xml:lang="en">Synonym number</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="STOFFSYNONYM" type="xsd:string">
				<xsd:annotation>
					<xsd:documentation xml:lang="de">Stoffname</xsd:documentation>
					<xsd:documentation xml:lang="fr">Nom de la substance</xsd:documentation>
					<xsd:documentation xml:lang="it">Nome sostanza</xsd:documentation>
					<xsd:documentation xml:lang="en">Substance name</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="QUELLE" type="xsd:string">
				<xsd:annotation>
					<xsd:documentation xml:lang="de">Quelle</xsd:documentation>
					<xsd:documentation xml:lang="fr">Source</xsd:documentation>
					<xsd:documentation xml:lang="it">Fonte</xsd:documentation>
					<xsd:documentation xml:lang="en">Source</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>

=== open-medication/open-medication-catalog/fixtures/ch/swissmedic/ogd/OGD-Stoff-Synonyme.XML
<?xml version='1.0' encoding='utf-8'?>
<ns0:SMC_Synonyme xmlns:ns0="http://ccsap.bit.admin.ch/SWISSMEDIC/LIMS_HMIT_KHZ" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://ccsap.bit.admin.ch/SWISSMEDIC/LIMS_HMIT_KHZ https://ogd.swissmedic.ch/hmd/ZL/172/Beschreibungen/OGD-Stoff-Synonyme.xsd"><SYNONYME><STOFF_ID>001F295B11971ED2B6E5CE185ADA3F9F</STOFF_ID><SYNONYM_CODE>LN</SYNONYM_CODE><LAUFENDE_NR>001</LAUFENDE_NR><STOFFSYNONYM>phenoli/phenoli sulfonatis/formaldehydi/urei condensatum natricum</STOFFSYNONYM><QUELLE /></SYNONYME><SYNONYME><STOFF_ID>001F295B11971ED2B6E5CE185ADADF9F</STOFF_ID><SYNONYM_CODE>LN</SYNONYM_CODE><LAUFENDE_NR>001</LAUFENDE_NR><STOFFSYNONYM>fluoridum</STOFFSYNONYM><QUELLE /></SYNONYME><SYNONYME><STOFF_ID>001F295B11971ED2B6E5CE4581755F9F</STOFF_ID><SYNONYM_CODE>LN</SYNONYM_CODE><LAUFENDE_NR>001</LAUFENDE_NR><STOFFSYNONYM>bromidum</STOFFSYNONYM><QUELLE>IUP</QUELLE></SYNONYME><SYNONYME><STOFF_ID>001F295B11971ED2B6E5CE8BA6429F9F</STOFF_ID><SYNONYM_CODE>LN</SYNONYM_CODE><LAUFENDE_NR>001</LAUFENDE_NR><STOFFSYNONYM>hydrogenocarbonas</STOFFSYNONYM><QUELLE>IUP</QUELLE></SYNONYME><SYNONYME><STOFF_ID>001F295B11971ED2B6E5CEA7C21E9F9F</STOFF_ID><SYNONYM_CODE>LN</SYNONYM_CODE><LAUFENDE_NR>001</LAUFENDE_NR><STOFFSYNONYM>aqua ad iniectabile</STOFFSYNONYM><QUELLE>EP</QUELLE></SYNONYME><SYNONYME><STOFF_ID>001F295B11971ED2B6E5CEA97341BF9F</STOFF_ID><SYNONYM_CODE>LN</SYNONYM_CODE><LAUFENDE_NR>001</LAUFENDE_NR><STOFFSYNONYM>chloridum</STOFFSYNONYM><QUELLE>IUP</QUELLE></SYNONYME><SYNONYME><STOFF_ID>001F295B11971ED2B6E5CEE7049A1F9F</STOFF_ID><SYNONYM_CODE>LN</SYNONYM_CODE><LAUFENDE_NR>001</LAUFENDE_NR><STOFFSYNONYM>iodidum</STOFFSYNONYM><QUELLE>IUP</QUELLE></SYNONYME><SYNONYME><STOFF_ID>001F295B11971ED2B6E5D3684C07DF9F</STOFF_ID><SYNONYM_CODE>LN</SYNONYM_CODE><LAUFENDE_NR>001</LAUFENDE_NR><STOFFSYNONYM>natrium</STOFFSYNONYM><QUELLE /></SYNONYME><SYNONYME><STOFF_ID>001F295B11971ED2B6E5D3684CFFFF9F</STOFF_ID><SYNONYM_CODE>LN</SYNONYM_CODE><LAUFENDE_NR>001</LAUFENDE_NR><STOFFSYNONYM>manganum</STOFFSYNONYM><QUELLE /></SYNONYME><SYNONYME><STOFF_ID>001F295B11971ED2B6E5D3684D009F9F</STOFF_ID><SYNONYM_CODE>LN</SYNONYM_CODE><LAUFENDE_NR>001</LAUFENDE_NR><STOFFSYNONYM>magnesium</STOFFSYNONYM><QUELLE /></SYNONYME><SYNONYME><STOFF_ID>001F295B11971ED2B6E5D3684D013F9F</STOFF_ID><SYNONYM_CODE>LN</SYNONYM_CODE><LAUFENDE_NR>001</LAUFENDE_NR><STOFFSYNONYM>lithium</STOFFSYNONYM><QUELLE>IUP</QUELLE></SYNONYME><SYNONYME><STOFF_ID>001F295B11971ED2B6E5D3692F19DF9F</STOFF_ID><SYNONYM_CODE>LN</SYNONYM_CODE><LAUFENDE_NR>001</LAUFENDE_NR><STOFFSYNONYM>kalium</STOFFSYNONYM><QUELLE /></SYNONYME><SYNONYME><STOFF_ID>001F295B11971ED2B6E5D377CC935F9F</STOFF_ID><SYNONYM_CODE>LN</SYNONYM_CODE><LAUFENDE_NR>001</LAUFENDE_NR><STOFFSYNONYM>ferrum</STOFFSYNONYM><QUELLE /></SYNONYME><SYNONYME><STOFF_ID>001F295B11971ED2B6E5D41B48451F9F</STOFF_ID><SYNONYM_CODE>LN</SYNONYM_CODE><LAUFENDE_NR>001</LAUFENDE_NR><STOFFSYNONYM>chloramphenicolum</STOFFSYNONYM><QUELLE>EP2</QUELLE></SYNONYME><SYNONYME><STOFF_ID>001F295B11971ED2B6E5D5319CD2DFA0</STOFF_ID><SYNONYM_CODE>LN</SYNONYM_CODE><LAUFENDE_NR>001</LAUFENDE_NR><STOFFSYNONYM>benzalkonii chloridum</STOFFSYNONYM><QUELLE>EP2</QUELLE></SYNONYME><SYNONYME><STOFF_ID>001F295B11971ED2B6E5D71695DC5FA0</STOFF_ID><SYNONYM_CODE>LN</SYNONYM_CODE><LAUFENDE_NR>001</LAUFENDE_NR><STOFFSYNONYM>sulfas</STOFFSYNONYM><QUELLE /></SYNONYME><SYNONYME><STOFF_ID>001F295B11971ED2B6E5D7798E541FA0</STOFF_ID><SYNONYM_CODE>LN</SYNONYM_CODE><LAUFENDE_NR>001</LAUFENDE_NR><STOFFSYNONYM>aqua purificata</STOFFSYNONYM><QUELLE>EP2</QUELLE></SYNONYME><SYNONYME><STOFF_ID>001F295B11971ED2B6E5D80C563C7FA0</STOFF_ID><SYNONYM_CODE>LN</SYNONYM_CODE><LAUFENDE_NR>001</LAUFENDE_NR><STOFFSYNONYM>sal ems</STOFFSYNONYM><QUELLE /></SYNONYME><SYNONYME><STOFF_ID>001F295B11971ED2B6E5D9DC6818BFA0</STOFF_ID><SYNONYM_CODE>LN</SYNONYM_CODE><LAUFENDE_NR>001</LAUFENDE_NR><STOFFSYNONYM>natrii hydroxidum</STOFFSYNONYM><QUELLE>EP</QUELLE></SYNONYME><SYNONYME><STOFF_ID>001F295B11971ED2B6E5DAC8A140DFA0</STOFF_ID><SYNONYM_CODE>LN</SYNONYM_CODE><LAUFENDE_NR>001</LAUFENDE_NR><STOFFSYNONYM>passiflorae herba</STOFFSYNONYM><QUELLE>EP</QUELLE></SYNONYME><SYNONYME><STOFF_ID>001F295B11971ED2B6E5DB26AA8E7FA0</STOFF_ID><SYNONYM_CODE>LN</SYNONYM_CODE><LAUFENDE_NR>001</LAUFENDE_NR><STOFFSYNONYM>oleae folium</STOFFSYNONYM><QUELLE>EP</QUELLE></SYNONYME><SYNONYME><STOFF_ID>001F295B11971ED2B6E5DBB42F203FA0</STOFF_ID><SYNONYM_CODE>LN</SYNONYM_CODE><LAUFENDE_NR>001</LAUFENDE_NR><STOFFSYNONYM>ilicis aquifolii folium</STOFFSYNONYM><QUELLE>HAG4</QUELLE></SYNONYME><SYNONYME><STOFF_ID>001F295B11971ED2B6E5DBE2A8F99FA0</STOFF_ID><SYNONYM_CODE>LN</SYNONYM_CODE><LAUFENDE_NR>001</LAUFENDE_NR><STOFFSYNONYM>lupuli flos</STOFFSYNONYM><QUELLE>EP</QUELLE></SYNONYME><SYNONYME><STOFF_ID>001F295B11971ED2B6E5DDE422A8FFA1</STOFF_ID><SYNONYM_CODE>LN</SYNONYM_CODE><LAUFENDE_NR>001</LAUFENDE_NR><STOFFSYNONYM>caryophyllatae herba</STOFFSYNONYM><QUELLE>HOPTB</QUELLE></SYNONYME><SYNONYME><STOFF_ID>001F295B11971ED2B6E5E0B811D8FFA2</STOFF_ID><SYNONYM_CODE>LN</SYNONYM_CODE><LAUFENDE_NR>001</LAUFENDE_NR><STOFFSYNONYM>crataegi folium cum flore</STOFFSYNONYM><QUELLE>EP</QUELLE></SYNONYME><SYNONYME><STOFF_ID>001F295B11971ED2B6E5E0BF56E5BFA2</STOFF_ID><SYNONYM_CODE>LN</SYNONYM_CODE><LAUFENDE_NR>001</LAUFENDE_NR><STOFFSYNONYM>crataegi fructus</STOFFSYNONYM><QUELLE>EP</QUELLE></SYNONYME><SYNONYME><STOFF_ID>001F295B11971ED2B6E5E3A48623BFA5</STOFF_ID><SYNONYM_CODE>LN</SYNONYM_CODE><LAUFENDE_NR>001</LAUFENDE_NR><STOFFSYNONYM>phosphas</STOFFSYNONYM><QUELLE /></SYNONYME><SYNONYME><STOFF_ID>001F295B11971ED2B6E5E7C978FE5FA6</STOFF_ID><SYNONYM_CODE>LN</SYNONYM_CODE><LAUFENDE_NR>001</LAUFENDE_NR><STOFFSYNONYM>nitras</STOFFSYNONYM><QUELLE /></SYNONYME><SYNONYME><STOFF_ID>001F295B11971ED2B6E5E80F497DBFA6</STOFF_ID><SYNONYM_CODE>LN</SYNONYM_CODE><LAUFENDE_NR>001</LAUFENDE_NR><STOFFSYNONYM>macrogolglyceroli ricinoleas</STOFFSYNONYM><QUELLE>EP</QUELLE></SYNONYME><SYNONYME><STOFF_ID>001F295B11971ED2B6E5F2821D717FAA</STOFF_ID><SYNONYM_CODE>LN</SYNONYM_CODE><LAUFENDE_NR>001</LAUFENDE_NR><STOFFSYNONYM>dexamethasoni natrii phosphas</STOFFSYNONYM><QUELLE>EP2</QUELLE></SYNONYME><SYNONYME><STOFF_ID>001F295B11971ED2B6E5F33CCE24BFAA</STOFF_ID><SYNONYM_CODE>LN</SYNONYM_CODE><LAUFENDE_NR>001</LAUFENDE_NR><STOFFSYNONYM>macrogolum 400</STOFFSYNONYM><QUELLE>EP2</QUELLE></SYNONYME><SYNONYME><STOFF_ID>001F295B11971ED2B6E5F4EEEB24DFAF</STOFF_ID><SYNONYM_CODE>LN</SYNONYM_CODE><LAUFENDE_NR>001</LAUFENDE_NR><STOFFSYNONYM>carbonas</STOFFSYNONYM><QUELLE>IUP</QUELLE></SYNONYME><SYNONYME><STOFF_ID>001F295B11971ED2B6E5FB2E0BF0DFB0</STOFF_ID><SYNONYM_CODE>LN</SYNONYM_CODE><LAUFENDE_NR>001</LAUFENDE_NR><STOFFSYNONYM>calcium</STOFFSYNONYM><QUELLE /></SYNONYME><SYNONYME><STOFF_ID>001F295B11971ED2B6E5FB3039BDBFB0</STOFF_ID><SYNONYM_CODE>LN</SYNONYM_CODE><LAUFENDE_NR>001</LAUFENDE_NR><STOFFSYNONYM>natrii sulfas anhydricus</STOFFSYNONYM><QUELLE>EP2</QUELLE></SYNONYME><SYNONYME><STOFF_ID>001F295B11971ED2B6E5FEA9BF79DFB1</STOFF_ID><SYNONYM_CODE>LN</SYNONYM_CODE><LAUFENDE_NR>001</LAUFENDE_NR><STOFFSYNONYM>dinatrii edetas</STOFFSYNONYM><QUELLE>EP</QUELLE></SYNONYME><SYNONYME><STOFF_ID>5CB9019C43551EEA8799EFC12A238AE5</STOFF_ID><SYNONYM_CODE>LN</SYNONYM_CODE><LAUFENDE_NR>001</LAUFENDE_NR><STOFFSYNONYM>natrii laureth-2-sulfas</STOFFSYNONYM><QUELLE /></SYNONYME></ns0:SMC_Synonyme>
