=== open-medication/open-medication-catalog/adapters/ch/swissmedic/xsd/OGD-User-Defined-Codes.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema targetNamespace="http://ccsap.bit.admin.ch/SWISSMEDIC/LIMS_HMIT_KHZ" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://ccsap.bit.admin.ch/SWISSMEDIC/LIMS_HMIT_KHZ" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3.org/2001/XMLSchema http://www.w3.org/2001/XMLSchema.xsd">
	<xsd:element name="SMC_Udc" type="OGD_Udc"/>
	<xsd:complexType name="OGD_Udc">
		<xsd:sequence>
			<xsd:element name="UDC" minOccurs="0" maxOccurs="unbounded" type="UDC"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="UDC">
		<xsd:sequence>
			<xsd:element name="SYSTEM_CODE" type="xsd:string">
				<xsd:annotation>
					<xsd:documentation xml:lang="de">Characterfeld der Länge 10</xsd:documentation>
					<xsd:documentation xml:lang="fr"></xsd:documentation>
					<xsd:documentation xml:lang="it">Campo di caratteri della lunghezza 10</xsd:documentation>
					<xsd:documentation xml:lang="en">Character field with length 10</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="USER_DEFINED_CODE" type="xsd:string">
				<xsd:annotation>
					<xsd:documentation xml:lang="de">UDC Name (Tabellenname)</xsd:documentation>
					<xsd:documentation xml:lang="fr"></xsd:documentation>
					<xsd:documentation xml:lang="it">Nome UDC (nome tabella)</xsd:documentation>
					<xsd:documentation xml:lang="en">UDC name (table name)</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="CODE_VALUE" type="xsd:string">
				<xsd:annotation>
					<xsd:documentation xml:lang="de">UDC Wert Swissmedic</xsd:documentation>
					<xsd:documentation xml:lang="fr"></xsd:documentation>
					<xsd:documentation xml:lang="it">Valore UDC Swissmedic</xsd:documentation>
					<xsd:documentation xml:lang="en">UDC value Swissmedic</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="SPRACH_CODE" type="xsd:string">
				<xsd:annotation>
					<xsd:documentation xml:lang="de">Sprachenschlüssel</xsd:documentation>
					<xsd:documentation xml:lang="fr">Language code</xsd:documentation>
					<xsd:documentation xml:lang="it">Codice lingua</xsd:documentation>
					<xsd:documentation xml:lang="en"></xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="BESCHREIBUNG_1" type="xsd:string">
				<xsd:annotation>
					<xsd:documentation xml:lang="de">UDC Beschreibung 1</xsd:documentation>
					<xsd:documentation xml:lang="fr">UDC description 1</xsd:documentation>
					<xsd:documentation xml:lang="it">Descrizione UDC 1</xsd:documentation>
					<xsd:documentation xml:lang="en"></xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="BESCHREIBUNG_2" type="xsd:string">
				<xsd:annotation>
					<xsd:documentation xml:lang="de">UDC Beschreibung 2</xsd:documentation>
					<xsd:documentation xml:lang="fr">UDC description 2</xsd:documentation>
					<xsd:documentation xml:lang="it">Descrizione UDC 2</xsd:documentation>
					<xsd:documentation xml:lang="en"></xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="BESCHREIBUNG_LANG" type="xsd:string">
				<xsd:annotation>
					<xsd:documentation xml:lang="de">UDC Beschreibung 3</xsd:documentation>
					<xsd:documentation xml:lang="fr">UDC description 3</xsd:documentation>
					<xsd:documentation xml:lang="it">Descrizione UDC 3</xsd:documentation>
					<xsd:documentation xml:lang="en"></xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>

=== open-medication/open-medication-catalog/fixtures/ch/swissmedic/ogd/OGD-User-Defined-Codes.XML
<?xml version='1.0' encoding='utf-8'?>
<ns0:SMC_Udc xmlns:ns0="http://ccsap.bit.admin.ch/SWISSMEDIC/LIMS_HMIT_KHZ" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://ccsap.bit.admin.ch/SWISSMEDIC/LIMS_HMIT_KHZ https://ogd.swissmedic.ch/hmd/ZL/172/Beschreibungen/OGD-User-Defined-Codes.xsd"><UDC><SYSTEM_CODE /><USER_DEFINED_CODE>COMP_NAME</USER_DEFINED_CODE><CODE_VALUE>(N/A)</CODE_VALUE><SPRACH_CODE>D</SPRACH_CODE><BESCHREIBUNG_1 /><BESCHREIBUNG_2 /><BESCHREIBUNG_LANG /></UDC><UDC><SYSTEM_CODE /><USER_DEFINED_CODE>COMP_NAME</USER_DEFINED_CODE><CODE_VALUE>(N/A)</CODE_VALUE><SPRACH_CODE>E</SPRACH_CODE><BESCHREIBUNG_1 /><BESCHREIBUNG_2 /><BESCHREIBUNG_LANG /></UDC><UDC><SYSTEM_CODE /><USER_DEFINED_CODE>COMP_NAME</USER_DEFINED_CODE><CODE_VALUE>(N/A)</CODE_VALUE><SPRACH_CODE>F</SPRACH_CODE><BESCHREIBUNG_1 /><BESCHREIBUNG_2 /><BESCHREIBUNG_LANG /></UDC><UDC><SYSTEM_CODE /><USER_DEFINED_CODE>COMP_NAME</USER_DEFINED_CODE><CODE_VALUE>(N/A)</CODE_VALUE><SPRACH_CODE>I</SPRACH_CODE><BESCHREIBUNG_1 /><BESCHREIBUNG_2 /><BESCHREIBUNG_LANG /></UDC><UDC><SYSTEM_CODE /><USER_DEFINED_CODE>DECLA_FORMAT</USER_DEFINED_CODE><CODE_VALUE>1</CODE_VALUE><SPRACH_CODE>D</SPRACH_CODE><BESCHREIBUNG_1>quantitativ deklarieren</BESCHREIBUNG_1><BESCHREIBUNG_2 /><BESCHREIBUNG_LANG /></UDC><UDC><SYSTEM_CODE /><USER_DEFINED_CODE>DECLA_FORMAT</USER_DEFINED_CODE><CODE_VALUE>1</CODE_VALUE><SPRACH_CODE>E</SPRACH_CODE><BESCHREIBUNG_1>declare in quantitative terms</BESCHREIBUNG_1><BESCHREIBUNG_2 /><BESCHREIBUNG_LANG /></UDC><UDC><SYSTEM_CODE /><USER_DEFINED_CODE>DECLA_FORMAT</USER_DEFINED_CODE><CODE_VALUE>2</CODE_VALUE><SPRACH_CODE>D</SPRACH_CODE><BESCHREIBUNG_1>qualitativ deklarieren</BESCHREIBUNG_1><BESCHREIBUNG_2 /><BESCHREIBUNG_LANG /></UDC><UDC><SYSTEM_CODE /><USER_DEFINED_CODE>DECLA_FORMAT</USER_DEFINED_CODE><CODE_VALUE>2</CODE_VALUE><SPRACH_CODE>E</SPRACH_CODE><BESCHREIBUNG_1>declare in qualitative terms</BESCHREIBUNG_1><BESCHREIBUNG_2 /><BESCHREIBUNG_LANG /></UDC><UDC><SYSTEM_CODE /><USER_DEFINED_CODE>DECLA_FORMAT</USER_DEFINED_CODE><CODE_VALUE>3</CODE_VALUE><SPRACH_CODE>D</SPRACH_CODE><BESCHREIBUNG_1>nicht deklarieren</BESCHREIBUNG_1><BESCHREIBUNG_2 /><BESCHREIBUNG_LANG /></UDC><UDC><SYSTEM_CODE /><USER_DEFINED_CODE>DECLA_FORMAT</USER_DEFINED_CODE><CODE_VALUE>3</CODE_VALUE><SPRACH_CODE>E</SPRACH_CODE><BESCHREIBUNG_1>do not declare</BESCHREIBUNG_1><BESCHREIBUNG_2 /><BESCHREIBUNG_LANG /></UDC><UDC><SYSTEM_CODE /><USER_DEFINED_CODE>DECLA_FORMAT</USER_DEFINED_CODE><CODE_VALUE>4</CODE_VALUE><SPRACH_CODE>D</SPRACH_CODE><BESCHREIBUNG_1>nie drucken!</BESCHREIBUNG_1><BESCHREIBUNG_2 /><BESCHREIBUNG_LANG /></UDC><UDC><SYSTEM_CODE /><USER_DEFINED_CODE>DECLA_FORMAT</USER_DEFINED_CODE><CODE_VALUE>4</CODE_VALUE><SPRACH_CODE>E</SPRACH_CODE><BESCHREIBUNG_1>never print!</BESCHREIBUNG_1><BESCHREIBUNG_2 /><BESCHREIBUNG_LANG /></UDC><UDC><SYSTEM_CODE /><USER_DEFINED_CODE>DF</USER_DEFINED_CODE><CODE_VALUE>AUL</CODE_VALUE><SPRACH_CODE>D</SPRACH_CODE><BESCHREIBUNG_1 /><BESCHREIBUNG_2>Augentropfen, Lösung</BESCHREIBUNG_2><BESCHREIBUNG_LANG /></UDC><UDC><SYSTEM_CODE /><USER_DEFINED_CODE>DF</USER_DEFINED_CODE><CODE_VALUE>AUL</CODE_VALUE><SPRACH_CODE>E</SPRACH_CODE><BESCHREIBUNG_1 /><BESCHREIBUNG_2>eye drops, solution</BESCHREIBUNG_2><BESCHREIBUNG_LANG /></UDC><UDC><SYSTEM_CODE /><USER_DEFINED_CODE>DF</USER_DEFINED_CODE><CODE_VALUE>AUL</CODE_VALUE><SPRACH_CODE>F</SPRACH_CODE><BESCHREIBUNG_1 /><BESCHREIBUNG_2>collyre en solution</BESCHREIBUNG_2><BESCHREIBUNG_LANG /></UDC><UDC><SYSTEM_CODE /><USER_DEFINED_CODE>DF</USER_DEFINED_CODE><CODE_VALUE>AUL</CODE_VALUE><SPRACH_CODE>I</SPRACH_CODE><BESCHREIBUNG_1 /><BESCHREIBUNG_2>collirio, soluzione</BESCHREIBUNG_2><BESCHREIBUNG_LANG /></UDC><UDC><SYSTEM_CODE /><USER_DEFINED_CODE>DF</USER_DEFINED_CODE><CODE_VALUE>BAD</CODE_VALUE><SPRACH_CODE>D</SPRACH_CODE><BESCHREIBUNG_1 /><BESCHREIBUNG_2>Badezusatz</BESCHREIBUNG_2><BESCHREIBUNG_LANG /></UDC><UDC><SYSTEM_CODE /><USER_DEFINED_CODE>DF</USER_DEFINED_CODE><CODE_VALUE>BAD</CODE_VALUE><SPRACH_CODE>E</SPRACH_CODE><BESCHREIBUNG_1 /><BESCHREIBUNG_2>Bath additive</BESCHREIBUNG_2><BESCHREIBUNG_LANG /></UDC><UDC><SYSTEM_CODE /><USER_DEFINED_CODE>DF</USER_DEFINED_CODE><CODE_VALUE>BAD</CODE_VALUE><SPRACH_CODE>F</SPRACH_CODE><BESCHREIBUNG_1 /><BESCHREIBUNG_2>Adjuvant de bain</BESCHREIBUNG_2><BESCHREIBUNG_LANG /></UDC><UDC><SYSTEM_CODE /><USER_DEFINED_CODE>DF</USER_DEFINED_CODE><CODE_VALUE>BAD</CODE_VALUE><SPRACH_CODE>I</SPRACH_CODE><BESCHREIBUNG_1 /><BESCHREIBUNG_2>Additivo per bagno</BESCHREIBUNG_2><BESCHREIBUNG_LANG /></UDC><UDC><SYSTEM_CODE /><USER_DEFINED_CODE>DF</USER_DEFINED_CODE><CODE_VALUE>PULIN</CODE_VALUE><SPRACH_CODE>D</SPRACH_CODE><BESCHREIBUNG_1 /><BESCHREIBUNG_2>Pulver zur Inhalation</BESCHREIBUNG_2><BESCHREIBUNG_LANG /></UDC><UDC><SYSTEM_CODE /><USER_DEFINED_CODE>DF</USER_DEFINED_CODE><CODE_VALUE>PULIN</CODE_VALUE><SPRACH_CODE>E</SPRACH_CODE><BESCHREIBUNG_1 /><BESCHREIBUNG_2>Inhalation powder</BESCHREIBUNG_2><BESCHREIBUNG_LANG /></UDC><UDC><SYSTEM_CODE /><USER_DEFINED_CODE>DF</USER_DEFINED_CODE><CODE_VALUE>PULIN</CODE_VALUE><SPRACH_CODE>F</SPRACH_CODE><BESCHREIBUNG_1 /><BESCHREIBUNG_2>Poudre pour inhalation</BESCHREIBUNG_2><BESCHREIBUNG_LANG /></UDC><UDC><SYSTEM_CODE /><USER_DEFINED_CODE>DF</USER_DEFINED_CODE><CODE_VALUE>PULIN</CODE_VALUE><SPRACH_CODE>I</SPRACH_CODE><BESCHREIBUNG_1 /><BESCHREIBUNG_2>Polvere per inalazione</BESCHREIBUNG_2><BESCHREIBUNG_LANG /></UDC><UDC><SYSTEM_CODE /><USER_DEFINED_CODE>DF</USER_DEFINED_CODE><CODE_VALUE>TROF</CODE_VALUE><SPRACH_CODE>D</SPRACH_CODE><BESCHREIBUNG_1 /><BESCHREIBUNG_2>Tropfen zum Einnehmen, Flüssigkeit</BESCHREIBUNG_2><BESCHREIBUNG_LANG /></UDC><UDC><SYSTEM_CODE /><USER_DEFINED_CODE>DF</USER_DEFINED_CODE><CODE_VALUE>TROF</CODE_VALUE><SPRACH_CODE>E</SPRACH_CODE><BESCHREIBUNG_1 /><BESCHREIBUNG_2>Oral drops, liquid</BESCHREIBUNG_2><BESCHREIBUNG_LANG /></UDC><UDC><SYSTEM_CODE /><USER_DEFINED_CODE>DF</USER_DEFINED_CODE><CODE_VALUE>TROF</CODE_VALUE><SPRACH_CODE>F</SPRACH_CODE><BESCHREIBUNG_1 /><BESCHREIBUNG_2>Liquide oral en gouttes</BESCHREIBUNG_2><BESCHREIBUNG_LANG /></UDC><UDC><SYSTEM_CODE /><USER_DEFINED_CODE>DF</USER_DEFINED_CODE><CODE_VALUE>TROF</CODE_VALUE><SPRACH_CODE>I</SPRACH_CODE><BESCHREIBUNG_1 /><BESCHREIBUNG_2>Gocce orali, liquido</BESCHREIBUNG_2><BESCHREIBUNG_LANG /></UDC><UDC><SYSTEM_CODE /><USER_DEFINED_CODE>MA_STATUS</USER_DEFINED_CODE><CODE_VALUE>A</CODE_VALUE><SPRACH_CODE>D</SPRACH_CODE><BESCHREIBUNG_1>angemeldet</BESCHREIBUNG_1><BESCHREIBUNG_2 /><BESCHREIBUNG_LANG /></UDC><UDC><SYSTEM_CODE /><USER_DEFINED_CODE>MA_STATUS</USER_DEFINED_CODE><CODE_VALUE>B</CODE_VALUE><SPRACH_CODE>D</SPRACH_CODE><BESCHREIBUNG_1>befristet</BESCHREIBUNG_1><BESCHREIBUNG_2 /><BESCHREIBUNG_LANG /></UDC><UDC><SYSTEM_CODE /><USER_DEFINED_CODE>MA_STATUS</USER_DEFINED_CODE><CODE_VALUE>BA</CODE_VALUE><SPRACH_CODE>D</SPRACH_CODE><BESCHREIBUNG_1>Befristete Zulassung abgelaufen</BESCHREIBUNG_1><BESCHREIBUNG_2 /><BESCHREIBUNG_LANG /></UDC><UDC><SYSTEM_CODE /><USER_DEFINED_CODE>MA_STATUS</USER_DEFINED_CODE><CODE_VALUE>D</CODE_VALUE><SPRACH_CODE>D</SPRACH_CODE><BESCHREIBUNG_1>nicht mehr zugelassen</BESCHREIBUNG_1><BESCHREIBUNG_2 /><BESCHREIBUNG_LANG /></UDC><UDC><SYSTEM_CODE /><USER_DEFINED_CODE>MA_STATUS</USER_DEFINED_CODE><CODE_VALUE>N</CODE_VALUE><SPRACH_CODE>D</SPRACH_CODE><BESCHREIBUNG_1>notifiziert</BESCHREIBUNG_1><BESCHREIBUNG_2 /><BESCHREIBUNG_LANG /></UDC><UDC><SYSTEM_CODE /><USER_DEFINED_CODE>MA_STATUS</USER_DEFINED_CODE><CODE_VALUE>S</CODE_VALUE><SPRACH_CODE>D</SPRACH_CODE><BESCHREIBUNG_1>sistiert</BESCHREIBUNG_1><BESCHREIBUNG_2 /><BESCHREIBUNG_LANG /></UDC><UDC><SYSTEM_CODE /><USER_DEFINED_CODE>MA_STATUS</USER_DEFINED_CODE><CODE_VALUE>U</CODE_VALUE><SPRACH_CODE>D</SPRACH_CODE><BESCHREIBUNG_1>nie zugelassen</BESCHREIBUNG_1><BESCHREIBUNG_2 /><BESCHREIBUNG_LANG /></UDC><UDC><SYSTEM_CODE /><USER_DEFINED_CODE>MA_STATUS</USER_DEFINED_CODE><CODE_VALUE>Z</CODE_VALUE><SPRACH_CODE>D</SPRACH_CODE><BESCHREIBUNG_1>zugelassen</BESCHREIBUNG_1><BESCHREIBUNG_2 /><BESCHREIBUNG_LANG /></UDC><UDC><SYSTEM_CODE /><USER_DEFINED_CODE>MA_TYPE</USER_DEFINED_CODE><CODE_VALUE>2</CODE_VALUE><SPRACH_CODE>D</SPRACH_CODE><BESCHREIBUNG_1>Prov. Registrierung</BESCHREIBUNG_1><BESCHREIBUNG_2 /><BESCHREIBUNG_LANG /></UDC><UDC><SYSTEM_CODE /><USER_DEFINED_CODE>MA_TYPE</USER_DEFINED_CODE><CODE_VALUE>2</CODE_VALUE><SPRACH_CODE>E</SPRACH_CODE><BESCHREIBUNG_1>provisional registration</BESCHREIBUNG_1><BESCHREIBUNG_2 /><BESCHREIBUNG_LANG /></UDC><UDC><SYSTEM_CODE /><USER_DEFINED_CODE>MA_TYPE</USER_DEFINED_CODE><CODE_VALUE>3</CODE_VALUE><SPRACH_CODE>D</SPRACH_CODE><BESCHREIBUNG_1>Hausspezialität IIb</BESCHREIBUNG_1><BESCHREIBUNG_2 /><BESCHREIBUNG_LANG /></UDC><UDC><SYSTEM_CODE /><USER_DEFINED_CODE>MA_TYPE</USER_DEFINED_CODE><CODE_VALUE>3</CODE_VALUE><SPRACH_CODE>E</SPRACH_CODE><BESCHREIBUNG_1>in-house speciality IIb</BESCHREIBUNG_1><BESCHREIBUNG_2 /><BESCHREIBUNG_LANG /></UDC><UDC><SYSTEM_CODE /><USER_DEFINED_CODE>MA_TYPE</USER_DEFINED_CODE><CODE_VALUE>4</CODE_VALUE><SPRACH_CODE>D</SPRACH_CODE><BESCHREIBUNG_1>Hausspezialität IIa</BESCHREIBUNG_1><BESCHREIBUNG_2 /><BESCHREIBUNG_LANG /></UDC><UDC><SYSTEM_CODE /><USER_DEFINED_CODE>MA_TYPE</USER_DEFINED_CODE><CODE_VALUE>4</CODE_VALUE><SPRACH_CODE>E</SPRACH_CODE><BESCHREIBUNG_1>in-house speciality IIa</BESCHREIBUNG_1><BESCHREIBUNG_2 /><BESCHREIBUNG_LANG /></UDC><UDC><SYSTEM_CODE /><USER_DEFINED_CODE>MA_TYPE</USER_DEFINED_CODE><CODE_VALUE>E</CODE_VALUE><SPRACH_CODE>D</SPRACH_CODE><BESCHREIBUNG_1>Exportzulassung</BESCHREIBUNG_1><BESCHREIBUNG_2 /><BESCHREIBUNG_LANG /></UDC><UDC><SYSTEM_CODE /><USER_DEFINED_CODE>MA_TYPE</USER_DEFINED_CODE><CODE_VALUE>E</CODE_VALUE><SPRACH_CODE>E</SPRACH_CODE><BESCHREIBUNG_1>authorisation for export</BESCHREIBUNG_1><BESCHREIBUNG_2 /><BESCHREIBUNG_LANG /></UDC><UDC><SYSTEM_CODE /><USER_DEFINED_CODE>MA_TYPE</USER_DEFINED_CODE><CODE_VALUE>H</CODE_VALUE><SPRACH_CODE>D</SPRACH_CODE><BESCHREIBUNG_1>Hauptzulassung</BESCHREIBUNG_1><BESCHREIBUNG_2 /><BESCHREIBUNG_LANG /></UDC><UDC><SYSTEM_CODE /><US
