=== open-medication/open-medication-catalog/adapters/ch/swissmedic/xsd/OGD-Deklarationen.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema targetNamespace="http://ccsap.bit.admin.ch/SWISSMEDIC/LIMS_HMIT_KHZ" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://ccsap.bit.admin.ch/SWISSMEDIC/LIMS_HMIT_KHZ" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3.org/2001/XMLSchema http://www.w3.org/2001/XMLSchema.xsd">
	<xsd:element name="SMC_Deklaration" type="OGD_Deklaration"/>
	<xsd:complexType name="DEKLARATION">
		<xsd:sequence>
			<xsd:element name="ZULASSUNGSNUMMER" type="xsd:integer">
				<xsd:annotation>
					<xsd:documentation xml:lang="de">Zulassungsnummer</xsd:documentation>
					<xsd:documentation xml:lang="fr">Numéro d’autorisation</xsd:documentation>
					<xsd:documentation xml:lang="it">Numero di omologazione</xsd:documentation>
					<xsd:documentation xml:lang="en">Authorisation number</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="SEQUENZNUMMER" type="xsd:integer">
				<xsd:annotation>
					<xsd:documentation xml:lang="de">Dosisstärke Nummer</xsd:documentation>
					<xsd:documentation xml:lang="fr">Numéro de dosage</xsd:documentation>
					<xsd:documentation xml:lang="it">Numero di dosaggio</xsd:documentation>
					<xsd:documentation xml:lang="en">Dosage strength number</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="KOMPONENTENNUMMER" type="xsd:integer">
				<xsd:annotation>
					<xsd:documentation xml:lang="de">Komponente</xsd:documentation>
					<xsd:documentation xml:lang="fr">Composant</xsd:documentation>
					<xsd:documentation xml:lang="it">Componente</xsd:documentation>
					<xsd:documentation xml:lang="en">Component</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="KOMPONENTE" type="xsd:string">
				<xsd:annotation>
					<xsd:documentation xml:lang="de">Komponentenname</xsd:documentation>
					<xsd:documentation xml:lang="fr">Nom du composant</xsd:documentation>
					<xsd:documentation xml:lang="it">Nome componente</xsd:documentation>
					<xsd:documentation xml:lang="en">Component name</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="ZEILENNUMMER" type="xsd:integer">
				<xsd:annotation>
					<xsd:documentation xml:lang="de">Deklarationszeile</xsd:documentation>
					<xsd:documentation xml:lang="fr">Ligne de déclaration</xsd:documentation>
					<xsd:documentation xml:lang="it">Riga dichiarazione</xsd:documentation>
					<xsd:documentation xml:lang="en">Declaration row</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="SORTIERUNG_ZEILENNUMMER" type="xsd:integer">
				<xsd:annotation>
					<xsd:documentation xml:lang="de">Sortierreihenfolge</xsd:documentation>
					<xsd:documentation xml:lang="fr">Ordre de tri</xsd:documentation>
					<xsd:documentation xml:lang="it">Sequenza di classificazione</xsd:documentation>
					<xsd:documentation xml:lang="en">Sort order</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="ZEILENTYP" type="xsd:string">
				<xsd:annotation>
					<xsd:documentation xml:lang="de">Deklarationstyp</xsd:documentation>
					<xsd:documentation xml:lang="fr">Type de déclaration</xsd:documentation>
					<xsd:documentation xml:lang="it">Tipo di dichiarazione</xsd:documentation>
					<xsd:documentation xml:lang="en">Declaration format</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="STOFF_ID" type="xsd:string">
				<xsd:annotation>
					<xsd:documentation xml:lang="de">Stoff Guid</xsd:documentation>
					<xsd:documentation xml:lang="fr">Identifiant global unique de la substance</xsd:documentation>
					<xsd:documentation xml:lang="it">GUID sostanza</xsd:documentation>
					<xsd:documentation xml:lang="en">Substance GUID</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="STOFFKATEGORIE" type="xsd:string">
				<xsd:annotation>
					<xsd:documentation xml:lang="de">Stoffkategorie</xsd:documentation>
					<xsd:documentation xml:lang="fr">Catégorie de substance</xsd:documentation>
					<xsd:documentation xml:lang="it">Categoria di sostanza</xsd:documentation>
					<xsd:documentation xml:lang="en">Substance category</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="MENGE" type="xsd:string">
				<xsd:annotation>
					<xsd:documentation xml:lang="de">Menge nur wenn «Deklarationsart = 1»</xsd:documentation>
					<xsd:documentation xml:lang="fr">Quantité seulement en cas de type de déclaration = «1» </xsd:documentation>
					<xsd:documentation xml:lang="it">Quantità solo tipo di dichiarazione «1»</xsd:documentation>
					<xsd:documentation xml:lang="en">Quantity only by Declaration type = «1»</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="MENGEN_EINHEIT" type="xsd:string">
				<xsd:annotation>
					<xsd:documentation xml:lang="de">Einheit nur wenn «Deklarationsart = 1»</xsd:documentation>
					<xsd:documentation xml:lang="fr">Unité seulement en cas de type de déclaration = «1»</xsd:documentation>
					<xsd:documentation xml:lang="it">Unità solo tipo di dichiarazione «1»</xsd:documentation>
					<xsd:documentation xml:lang="en">Unit only by Declaration type = «1»</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="DEKLARATIONSART" type="xsd:integer">
				<xsd:annotation>
					<xsd:documentation xml:lang="de">Deklarationsart «1» oder «2»</xsd:documentation>
					<xsd:documentation xml:lang="fr">Type de déclaration «1» ou «2»</xsd:documentation>
					<xsd:documentation xml:lang="it">Tipo di dichiarazione «1» oder «2»</xsd:documentation>
					<xsd:documentation xml:lang="en">Declaration type «1» or «2»</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="OGD_Deklaration">
		<xsd:sequence>
			<xsd:element name="DEKLARATION" minOccurs="0" maxOccurs="unbounded" type="DEKLARATION"/>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>

=== open-medication/open-medication-catalog/fixtures/ch/swissmedic/ogd/OGD-Deklarationen.XML
<?xml version='1.0' encoding='utf-8'?>
<ns0:SMC_Deklaration xmlns:ns0="http://ccsap.bit.admin.ch/SWISSMEDIC/LIMS_HMIT_KHZ" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://ccsap.bit.admin.ch/SWISSMEDIC/LIMS_HMIT_KHZ https://ogd.swissmedic.ch/hmd/ZL/172/Beschreibungen/OGD-Deklarationen.xsd"><DEKLARATION><ZULASSUNGSNUMMER>10029</ZULASSUNGSNUMMER><SEQUENZNUMMER>2</SEQUENZNUMMER><KOMPONENTENNUMMER>1</KOMPONENTENNUMMER><KOMPONENTE>(N/A)</KOMPONENTE><ZEILENNUMMER>2</ZEILENNUMMER><SORTIERUNG_ZEILENNUMMER>2</SORTIERUNG_ZEILENNUMMER><ZEILENTYP>S</ZEILENTYP><STOFF_ID>001F295B11971ED2B6E5DBB42F203FA0</STOFF_ID><STOFFKATEGORIE>WIRKS</STOFFKATEGORIE><MENGE>31</MENGE><MENGEN_EINHEIT>MG</MENGEN_EINHEIT><DEKLARATIONSART>1</DEKLARATIONSART></DEKLARATION><DEKLARATION><ZULASSUNGSNUMMER>10029</ZULASSUNGSNUMMER><SEQUENZNUMMER>2</SEQUENZNUMMER><KOMPONENTENNUMMER>1</KOMPONENTENNUMMER><KOMPONENTE>(N/A)</KOMPONENTE><ZEILENNUMMER>3</ZEILENNUMMER><SORTIERUNG_ZEILENNUMMER>3</SORTIERUNG_ZEILENNUMMER><ZEILENTYP>S</ZEILENTYP><STOFF_ID>001F295B11971ED2B6E5DB26AA8E7FA0</STOFF_ID><STOFFKATEGORIE>WIRKS</STOFFKATEGORIE><MENGE>31</MENGE><MENGEN_EINHEIT>MG</MENGEN_EINHEIT><DEKLARATIONSART>1</DEKLARATIONSART></DEKLARATION><DEKLARATION><ZULASSUNGSNUMMER>10029</ZULASSUNGSNUMMER><SEQUENZNUMMER>2</SEQUENZNUMMER><KOMPONENTENNUMMER>1</KOMPONENTENNUMMER><KOMPONENTE>(N/A)</KOMPONENTE><ZEILENNUMMER>4</ZEILENNUMMER><SORTIERUNG_ZEILENNUMMER>4</SORTIERUNG_ZEILENNUMMER><ZEILENTYP>S</ZEILENTYP><STOFF_ID>001F295B11971ED2B6E5E0BF56E5BFA2</STOFF_ID><STOFFKATEGORIE>WIRKS</STOFFKATEGORIE><MENGE>31</MENGE><MENGEN_EINHEIT>MG</MENGEN_EINHEIT><DEKLARATIONSART>1</DEKLARATIONSART></DEKLARATION><DEKLARATION><ZULASSUNGSNUMMER>10029</ZULASSUNGSNUMMER><SEQUENZNUMMER>2</SEQUENZNUMMER><KOMPONENTENNUMMER>1</KOMPONENTENNUMMER><KOMPONENTE>(N/A)</KOMPONENTE><ZEILENNUMMER>5</ZEILENNUMMER><SORTIERUNG_ZEILENNUMMER>8</SORTIERUNG_ZEILENNUMMER><ZEILENTYP>S</ZEILENTYP><STOFF_ID>001F295B11971ED2B6E5DBE2A8F99FA0</STOFF_ID><STOFFKATEGORIE>WIRKS</STOFFKATEGORIE><MENGE>31</MENGE><MENGEN_EINHEIT>MG</MENGEN_EINHEIT><DEKLARATIONSART>1</DEKLARATIONSART></DEKLARATION><DEKLARATION><ZULASSUNGSNUMMER>10029</ZULASSUNGSNUMMER><SEQUENZNUMMER>2</SEQUENZNUMMER><KOMPONENTENNUMMER>1</KOMPONENTENNUMMER><KOMPONENTE>(N/A)</KOMPONENTE><ZEILENNUMMER>6</ZEILENNUMMER><SORTIERUNG_ZEILENNUMMER>7</SORTIERUNG_ZEILENNUMMER><ZEILENTYP>S</ZEILENTYP><STOFF_ID>001F295B11971ED2B6E5DAC8A140DFA0</STOFF_ID><STOFFKATEGORIE>WIRKS</STOFFKATEGORIE><MENGE>46</MENGE><MENGEN_EINHEIT>MG</MENGEN_EINHEIT><DEKLARATIONSART>1</DEKLARATIONSART></DEKLARATION><DEKLARATION><ZULASSUNGSNUMMER>10029</ZULASSUNGSNUMMER><SEQUENZNUMMER>2</SEQUENZNUMMER><KOMPONENTENNUMMER>1</KOMPONENTENNUMMER><KOMPONENTE>(N/A)</KOMPONENTE><ZEILENNUMMER>7</ZEILENNUMMER><SORTIERUNG_ZEILENNUMMER>6</SORTIERUNG_ZEILENNUMMER><ZEILENTYP>S</ZEILENTYP><STOFF_ID>001F295B11971ED2B6E5DDE422A8FFA1</STOFF_ID><STOFFKATEGORIE>WIRKS</STOFFKATEGORIE><MENGE>62</MENGE><MENGEN_EINHEIT>MG</MENGEN_EINHEIT><DEKLARATIONSART>1</DEKLARATIONSART></DEKLARATION><DEKLARATION><ZULASSUNGSNUMMER>10029</ZULASSUNGSNUMMER><SEQUENZNUMMER>2</SEQUENZNUMMER><KOMPONENTENNUMMER>1</KOMPONENTENNUMMER><KOMPONENTE>(N/A)</KOMPONENTE><ZEILENNUMMER>8</ZEILENNUMMER><SORTIERUNG_ZEILENNUMMER>5</SORTIERUNG_ZEILENNUMMER><ZEILENTYP>S</ZEILENTYP><STOFF_ID>001F295B11971ED2B6E5E0B811D8FFA2</STOFF_ID><STOFFKATEGORIE>WIRKS</STOFFKATEGORIE><MENGE>93</MENGE><MENGEN_EINHEIT>MG</MENGEN_EINHEIT><DEKLARATIONSART>1</DEKLARATIONSART></DEKLARATION><DEKLARATION><ZULASSUNGSNUMMER>10167</ZULASSUNGSNUMMER><SEQUENZNUMMER>1</SEQUENZNUMMER><KOMPONENTENNUMMER>1</KOMPONENTENNUMMER><KOMPONENTE>(N/A)</KOMPONENTE><ZEILENNUMMER>10</ZEILENNUMMER><SORTIERUNG_ZEILENNUMMER>9</SORTIERUNG_ZEILENNUMMER><ZEILENTYP>S</ZEILENTYP><STOFF_ID>001F295B11971ED2B6E5D3684D013F9F</STOFF_ID><STOFFKATEGORIE>WIRKS</STOFFKATEGORIE><MENGE>0.21</MENGE><MENGEN_EINHEIT>MGG</MENGEN_EINHEIT><DEKLARATIONSART>1</DEKLARATIONSART></DEKLARATION><DEKLARATION><ZULASSUNGSNUMMER>10167</ZULASSUNGSNUMMER><SEQUENZNUMMER>1</SEQUENZNUMMER><KOMPONENTENNUMMER>1</KOMPONENTENNUMMER><KOMPONENTE>(N/A)</KOMPONENTE><ZEILENNUMMER>11</ZEILENNUMMER><SORTIERUNG_ZEILENNUMMER>10</SORTIERUNG_ZEILENNUMMER><ZEILENTYP>S</ZEILENTYP><STOFF_ID>001F295B11971ED2B6E5D3684D009F9F</STOFF_ID><STOFFKATEGORIE>WIRKS</STOFFKATEGORIE><MENGE>0.291</MENGE><MENGEN_EINHEIT>MGG</MENGEN_EINHEIT><DEKLARATIONSART>1</DEKLARATIONSART></DEKLARATION><DEKLARATION><ZULASSUNGSNUMMER>10167</ZULASSUNGSNUMMER><SEQUENZNUMMER>1</SEQUENZNUMMER><KOMPONENTENNUMMER>1</KOMPONENTENNUMMER><KOMPONENTE>(N/A)</KOMPONENTE><ZEILENNUMMER>12</ZEILENNUMMER><SORTIERUNG_ZEILENNUMMER>11</SORTIERUNG_ZEILENNUMMER><ZEILENTYP>S</ZEILENTYP><STOFF_ID>001F295B11971ED2B6E5FB2E0BF0DFB0</STOFF_ID><STOFFKATEGORIE>WIRKS</STOFFKATEGORIE><MENGE>0.016</MENGE><MENGEN_EINHEIT>MGG</MENGEN_EINHEIT><DEKLARATIONSART>1</DEKLARATIONSART></DEKLARATION><DEKLARATION><ZULASSUNGSNUMMER>10167</ZULASSUNGSNUMMER><SEQUENZNUMMER>1</SEQUENZNUMMER><KOMPONENTENNUMMER>1</KOMPONENTENNUMMER><KOMPONENTE>(N/A)</KOMPONENTE><ZEILENNUMMER>13</ZEILENNUMMER><SORTIERUNG_ZEILENNUMMER>12</SORTIERUNG_ZEILENNUMMER><ZEILENTYP>S</ZEILENTYP><STOFF_ID>001F295B11971ED2B6E5D3684CFFFF9F</STOFF_ID><STOFFKATEGORIE>WIRKS</STOFFKATEGORIE><MENGE>0.00011</MENGE><MENGEN_EINHEIT>MGG</MENGEN_EINHEIT><DEKLARATIONSART>1</DEKLARATIONSART></DEKLARATION><DEKLARATION><ZULASSUNGSNUMMER>10167</ZULASSUNGSNUMMER><SEQUENZNUMMER>1</SEQUENZNUMMER><KOMPONENTENNUMMER>1</KOMPONENTENNUMMER><KOMPONENTE>(N/A)</KOMPONENTE><ZEILENNUMMER>14</ZEILENNUMMER><SORTIERUNG_ZEILENNUMMER>13</SORTIERUNG_ZEILENNUMMER><ZEILENTYP>S</ZEILENTYP><STOFF_ID>001F295B11971ED2B6E5D377CC935F9F</STOFF_ID><STOFFKATEGORIE>WIRKS</STOFFKATEGORIE><MENGE>0.00245</MENGE><MENGEN_EINHEIT>MGG</MENGEN_EINHEIT><DEKLARATIONSART>1</DEKLARATIONSART></DEKLARATION><DEKLARATION><ZULASSUNGSNUMMER>10167</ZULASSUNGSNUMMER><SEQUENZNUMMER>1</SEQUENZNUMMER><KOMPONENTENNUMMER>1</KOMPONENTENNUMMER><KOMPONENTE>(N/A)</KOMPONENTE><ZEILENNUMMER>15</ZEILENNUMMER><SORTIERUNG_ZEILENNUMMER>14</SORTIERUNG_ZEILENNUMMER><ZEILENTYP>S</ZEILENTYP><STOFF_ID>001F295B11971ED2B6E5CE185ADADF9F</STOFF_ID><STOFFKATEGORIE>WIRKS</STOFFKATEGORIE><MENGE>0.078</MENGE><MENGEN_EINHEIT>MGG</MENGEN_EINHEIT><DEKLARATIONSART>1</DEKLARATIONSART></DEKLARATION><DEKLARATION><ZULASSUNGSNUMMER>10167</ZULASSUNGSNUMMER><SEQUENZNUMMER>1</SEQUENZNUMMER><KOMPONENTENNUMMER>1</KOMPONENTENNUMMER><KOMPONENTE>(N/A)</KOMPONENTE><ZEILENNUMMER>16</ZEILENNUMMER><SORTIERUNG_ZEILENNUMMER>15</SORTIERUNG_ZEILENNUMMER><ZEILENTYP>S</ZEILENTYP><STOFF_ID>001F295B11971ED2B6E5CE4581755F9F</STOFF_ID><STOFFKATEGORIE>WIRKS</STOFFKATEGORIE><MENGE>0.202</MENGE><MENGEN_EINHEIT>MGG</MENGEN_EINHEIT><DEKLARATIONSART>1</DEKLARATIONSART></DEKLARATION><DEKLARATION><ZULASSUNGSNUMMER>10167</ZULASSUNGSNUMMER><SEQUENZNUMMER>1</SEQUENZNUMMER><KOMPONENTENNUMMER>1</KOMPONENTENNUMMER><KOMPONENTE>(N/A)</KOMPONENTE><ZEILENNUMMER>17</ZEILENNUMMER><SORTIERUNG_ZEILENNUMMER>16</SORTIERUNG_ZEILENNUMMER><ZEILENTYP>S</ZEILENTYP><STOFF_ID>001F295B11971ED2B6E5CEE7049A1F9F</STOFF_ID><STOFFKATEGORIE>WIRKS</STOFFKATEGORIE><MENGE>0.00432</MENGE><MENGEN_EINHEIT>MGG</MENGEN_EINHEIT><DEKLARATIONSART>1</DEKLARATIONSART></DEKLARATION><DEKLARATION><ZULASSUNGSNUMMER>10167</ZULASSUNGSNUMMER><SEQUENZNUMMER>1</SEQUENZNUMMER><KOMPONENTENNUMMER>1</KOMPONENTENNUMMER><KOMPONENTE>(N/A)</KOMPONENTE><ZEILENNUMMER>18</ZEILENNUMMER><SORTIERUNG_ZEILENNUMMER>17</SORTIERUNG_ZEILENNUMMER><ZEILENTYP>S</ZEILENTYP><STOFF_ID>001F295B11971ED2B6E5E7C978FE5FA6</STOFF_ID><STOFFKATEGORIE>WIRKS</STOFFKATEGORIE><MENGE>0.355</MENGE><MENGEN_EINHEIT>MGG</MENGEN_EINHEIT><DEKLARATIONSART>1</DEKLARATIONSART></DEKLARATION><DEKLARATION><ZULASSUNGSNUMMER>10167</ZULASSUNGSNUMMER><SEQUENZNUMMER>1</SEQUENZNUMMER><KOMPONENTENNUMMER>1</KOMPONENTENNUMMER><KOMPONENTE>(N/A)</KOMPONENTE><ZEILENNUMMER>2</ZEILENNUMMER><SORTIERUNG_ZEILENNUMMER>1</SORTIERUNG_ZEILENNUMMER><ZEILENTYP>S</ZEILENTYP><STOFF_ID>001F295B11971ED2B6E5D80C563C7FA0</STOFF_ID><STOFFKATEGORIE>WIRKS</STOFFKATEGORIE><MENGE>100</MENGE><MENGEN_EINHEIT>PMM</MENGEN_EINHEIT><DEKLARATIONSART>1</DEKLARATIONSART></DEKLARATION><DEKLARATION><ZULASSUNGSNUMMER>10167</ZULASSUNGSNUMMER><SEQUENZNUMMER>1</SEQUENZNUMMER><KOMPONENTENNUMMER>1</KOMPONENTENNUMMER><KOMPONENTE>(N/A)</KOMPONENTE><ZEILENNUMMER>4</ZEILENNUMMER><SORTIERUNG_ZEILENNUMMER>3</SORTIERUNG_ZEILENNUMMER><ZEILENTYP>S</ZEILENTYP><STOFF_ID>001F295B11971ED2B6E5D3684C07DF9F</STOFF_ID><STOFFKATEGORIE>WIRKS</STOFFKATEGORIE><MENGE>308.7</MENGE><MENGEN_EINHEIT>MGG</MENGEN_EINHEIT><DEKLARATIONSART>1</DEKLARATIONSART></DEKLARATION><DEKLARATION><ZULASSUNGSNUMMER>10167</ZULASSUNGSNUMMER><SEQUENZNUMMER>1</SEQUENZNUMMER><KOMPONENTENNUMMER>1</KOMPONENTENNUMMER><KOMPONENTE>(N/A)</KOMPONENTE><ZEILENNUMMER>5</ZEILENNUMMER><SORTIERUNG_ZEILENNUMMER>4</SORTIERUNG_ZEILENNUMMER><ZEILENTYP>S</ZEILENTYP><STOFF_ID>001F295B11971ED2B6E5D3692F19DF9F</STOFF_ID><STOFFKATEGORIE>WIRKS</STOFFKATEGORIE><MENGE>6.11</MENGE><MENGEN_EINHEIT>MGG</MENGEN_EINHEIT><DEKLARATIONSART>1</DEKLARATIONSART></DEKLARATION><DEKLARATION><ZULASSUNGSNUMMER>10167</ZULASSUNGSNUMMER><SEQUENZNUMMER>1</SEQUENZNUMMER><KOMPONENTENNUMMER>1</KOMPONENTENNUMMER><KOMPONENTE>(N/A)</KOMPONENTE><ZEILENNUMMER>6</ZEILENNUMMER><SORTIERUNG_ZEILENNUMMER>5</SORTIERUNG_ZEILENNUMMER><ZEILENTYP>S</ZEILENTYP><STOFF_ID>001F295B11971ED2B6E5CEA97341BF9F</STOFF_ID><STOFFKATEGORIE>WIRKS</STOFFKATEGORIE><MENGE>188.4</MENGE><MENGEN_EINHEIT>MGG</MENGEN_EINHEIT><DEKLARATIONSART>1</DEKLARATIONSART></DEKLARATION><DEKLARATION><ZULASSUNGSNUMMER>10167</ZULASSUNGSNUMMER><SEQUENZNUMMER>1</SEQUENZNUMMER><KOMPONENTENNUMMER>1</KOMPONENTENNUMMER><KOMPONENTE>(N/A)</KOMPONENTE><ZEILENNUMMER>7</ZEILENNUMMER><SORTIERUNG_ZEILENNUMMER>6</SORTIERUNG_ZEILENNUMMER><ZEILENTYP>S</ZEILENTYP><STOFF_ID>001F295B11971ED2B6E5CE8BA6429F9F</STOFF_ID><STOFFKATEGORIE>WIRKS</STOFFKATEGORIE><MENGE>474.4</MENGE><MENGEN_EINHEIT>MGG</MENGEN_EINHEIT><DEKLARATIONSART>1</DEKLARATIONSART></DEKLARATION><DEKLARATION><ZULASSUNGSNU
